apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aggregator-service-2
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: aggregator-service
    spec:
      containers:
      - name: aggregator-service
        image: nginx
        ports:
        - containerPort: 8080
